FROM nginx

COPY index.html /usr/share/nginx/html
COPY styles.css /usr/share/nginx/html
COPY html /usr/share/nginx/html/html
COPY js /usr/share/nginx/html/js
COPY styles /usr/share/nginx/html/styles
COPY constants.js /usr/share/nginx/html
COPY helpers.js /usr/share/nginx/html
