version: '3.3'

services:
  backend:
    depends_on:
      - mysql
    build:
      context: ./backend
    image: class_exchange_backend
    container_name: class_exchange_backend
    hostname: backend
    networks: 
      - class_exchange_network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DSN=${DSN}
      - BACKEND_PORT=${BACKEND_PORT}

  frontend:
    build:
        context: ./frontend
    image: class_exchange_frontend
    container_name: class_exchange_frontend
    ports: 
    - "${FRONTEND_PORT}:80"
    environment:
    - NGINX_PORT=80

  mysql:
    image: mysql:latest
    container_name: class_exchange_mysql
    hostname: db
    networks: 
      - class_exchange_network
    volumes:
      - class_exchange:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

volumes:
  class_exchange:

networks:
  class_exchange_network:
    driver: bridge
